### ISSUE TITLE
robust rspec matchers

### ISSUE THREAD

**Issue by wnadeau** [hired/reactor#15]
Neither of the following should cause a reactor matcher to fail (but they currently do)
1. adding a second event to the test lifecycle 
2. changing the order in which events are fired in the test lifecycle 

It only really works well when asserting that just one event was fired when indeed, only one event is fired.

It fails incorrectly when a second event (whether or not it's related) is also fired within the test's covered code. (Because it is only matching that one event gets called with a .should_receive.) For example, check this snippet from one of our tests where we had to ensure that a specific event was fired (even though other events were being fired in the context).

![image](https://cloud.githubusercontent.com/assets/169076/3403857/b0321e8e-fd6a-11e3-8d76-acb9e277d20d.png)

Ideally Reactor will provide more choices in the style of event assertions being made. Perhaps a "stub" vs "assert" pattern applied here like they do in the webmock gem, for example, would help alleviate this pain. It should be up to the consuming developer to decide if they should just stub an event (or any) at the beginning of the test (like they would stub a web request) or if they should make some kind of stronger assertion along the lines of "this event will fire"

Historically a "publishes_events" multi-event matcher was introduced, but there is still a tight coupling between the tests and the code because we have to be explicit about each event that is fired. (So when we add another event somewhere, we may have to go update the assertions to include it, lame.)

**Comment by agius** [comment]
Other problem: `a_hash_including` seems to fail when the arguments don't match _exactly_ . It would be great to specify just a subset of the data passed in, or allow things like `match_array` for data elements.

To that end, I'm working on something similar to `ActionMailer::Base.deliveries` and [Sidekiq's test job queue](https://github.com/mperham/sidekiq/wiki/Testing#testing-worker-queueing-fake) over on [this branch](https://github.com/hired/reactor/tree/feature/record-test-events). That way, you wouldn't have to stub the publish method, and find multiple events fired and run expectations on them.

One problem: where do I put the code to record the event? Putting it in `Subscribable` seems to be giving me a lot of issues. Could I drop that interceptor into `Event.publish` directly?

cc @wnadeau @dashkb

**Comment by dashkb** [comment]
This may be word-mincing, but rather than 'dropping code in' to `Event.publish` it may be cleaner/safer to wrap/decorate it with the intercepting-and-shoving-into-a-thing code.

Or, separate thought, it may be more Reactor-y to run a subscriber to do it, like `ActivityLogger` but just for testing and asserting about.

**Comment by wnadeau** [comment]
indeed, I'd **prefer** to not have any test code in lib/reactor/event, employing a module that only gets mixed in when you `require 'reactor/testing'`, decorating whatever methods it needs to track whatever.

However, we already have TEST_MODE shit just dumped in-line, so @agius's current implementation is just following that pattern. 

I'm also aware that this preference is cosmetic and only useful if the amount of in-line stuff gets large enough to bloat up the primary implementation. (in this case, I believe we are actually getting to that point).

I'm also aware that this creates more work for the implementer, which is probably why this larger piece, now that it has a solid design behind it, can & should be executed as a story in our infra backlog.

**Comment by agius** [comment]
Tried a few stabs at this, and [this line](https://github.com/hired/reactor/blob/master/lib/reactor/models/concerns/subscribable.rb#L22) is where it all goes to hell. Defining classes at runtime is **wrong** :broken_heart:

**Comment by dashkb** [comment]
> Defining classes at runtime is wrong

I don't think I'd go that far... plus, it's always runtime.  It's part of the fun/magic/power of Ruby, but of course can be pointed at foot.

**Comment by wnadeau** [comment]
by doubling down on rspec's allow/expect pattern (and gutting TEST_MODE entirely), this is less of a concern. If you need more features for comparison, just `expect(Reactor::Event).to receive(:publish).with(whatever)` and do it just like you would _any other method_!. 

🎉
