### ISSUE TITLE
changing dependencies from sidekiq to activejob

### ISSUE THREAD

**Issue by wnadeau** [hired/reactor#28]
we made this thing work in rails 4, but we didn't really consider cleaning up the API.

i probably don't have to explain the benefits of depending on an adapter instead of a specific background job implementation.

primarily, i would love to be able to use this in side projects where I don't want to pay for a background worker just yet, but do want the same code patterns

i've started looking at all of the dependencies/bindings we have thus far, and it looks non-trivial to accomplish this kind of change, so I wanted to start the conversation here before gutting a bunch of shit. 
## Benefits
- uses new [rails GlobalID](https://github.com/rails/rails/tree/master/activejob#globalid-support) instead of serializing activerecord objects as *_type and *_id parameters.
- allows starter projects to avoid paying for worker processes until needed
- major incentive to perform feature-removal & decomposition/simplification of gem responsibilities (something we've deprioritized lately)
## Costs
- major version release / breaking changes
- Unfortunately I'm pretty sure we have to consider completing #21 before doing this because rescheduling [just isn't really a concern of background jobs](http://stackoverflow.com/questions/28212817/efficiently-reschedule-activejob-resque-sidekiq).
- will require a careful / delicate migration strategy for production setup

I'll begin considering this against other priorities at Hired, as a case can be made for the simplification of our toolset and removal of a potential time-bomb sitting in #21.

**Comment by wnadeau** [comment]
cc @heythisisnate @joelmichael @dashkb and @schlende

**Comment by heythisisnate** [comment]
I think this is a great idea for 1.0. RailsConf hack project?

**Comment by schlende** [comment]
Pretty interested in getting #21 out of the way. I keep needing that kind of functionality and feel weird about future jobs sitting in Redis.

**Comment by wnadeau** [comment]
this is pretty close to a total re-write.

* Reactor::Publishable is being removed, recommend users switch to [hired/chron](http://github.com/hired/chron) for this functionality.
* Reactor::Subscriber will need an ActiveJob wrapper, no longer using Sidekiq's `Class.delay` hack
* The whole static subscriber pattern needs to inherit from ActiveJob... may be easier to dump that pattern and go with a more sensible parameterized container job. (Like in hired/chron)

**Comment by wnadeau** [comment]
oh yeah, also it looks like the GlobalId support only applies to bare/unnamed arguments, so we can't really use it in this case. =(

discovered this "the hard way" by seeing this while TDD http://edgeapi.rubyonrails.org/classes/ActiveJob/SerializationError.html

oh well, the old serializing code will still work

**Comment by wnadeau** [comment]
I still get jokes about ActiveJob vs. Sidekiq on my twitter feed. 

❤️ you rails but it sounds like most people are staying on vanilla sidekiq.

feel free to resurrect this if want!
