### ISSUE TITLE
can't supply a 'data' key to an event

### ISSUE THREAD

**Issue by wnadeau** [hired/reactor#41]
`Reactor::Event.publish(:some_event, with: 'some', data: {stuffed_in: 'here'})`

It appears that `data` key will collide with the internal implementation that uses an instance variable named `@data` and allows loose access to setters/getters on it through `method_missing`.

The end result is that you'll overwrite key/values previously defined in the event data packet when using the `data` key. 

Surely we can just obfuscate the internal implementation a little more or something.

**Comment by satyap2** [comment]
Internal `data` key? Should be `_data` :P

**Comment by satyap2** [comment]
Hmm, that is going to break any code that uses `event.data` :(

**Comment by satyap2** [comment]
@wnadeau there's a PR #43, in case you missed it. Admittedly, my first time hacking on Reactor, I may have done something dumb.

**Comment by wnadeau** [comment]
oh yeah we did this already
