### ISSUE TITLE
RFC: UUIDs on events

### ISSUE THREAD

**Issue by satyap2** [hired/reactor#65]
It would be nice is Reactor generated and added UUIDs on events.

We're generating events and sending them off to two destinations: Postgres and Kinesis.

For isolation reasons, this is being handled by two different `*` listeners.

It might be good to have an identifier i.e. UUID to match events across the systems.

We can't really generate the same UUID in both listeners, if only because timestamps will likely differ.

So it would be nice if Reactor generated the UUID before the event reaches subscribers.

Reactor could skip generating the UUID if the event already has a `uuid` key.

Thoughts invited!

**Comment by sbisker** [comment]
+1 to this. I think I almost built this at some point - an identifier that can both be returned to the creator of the event, and referenced where the event is processed.

**Comment by satyap2** [comment]
If there are no disagreements, I'll throw up a PR.

**Comment by satyap2** [comment]
Sorry, folks, this *already exists*!
